services:
  price_db:
    image: postgres:latest
    container_name: price_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - price_db:/var/lib/postgresql/data

  price_hero:
    build:
      context: .
    container_name: price_hero
    environment:
      - SECRET_PATH=config/.secrets.json
    depends_on:
      - price_db
    volumes:
      - $HOME/.aws/credentials:/root/.aws/credentials:ro
      - .:/app
    stdin_open: true
    tty: true
    entrypoint: ["python", "cli.py"]

volumes:
  price_db:
