name: Code Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  style:
    runs-on: ubuntu-latest
    name: Check style formatting
    strategy:
      matrix:
        python-version: [3.10]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - run: python3 -m pip install black
      - run: black .
